# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMz0xpyxHdnaeT8ylgjjdPRFuzhw5duH
"""

def majmoe(t):
  sum=0
  while t !=0:
    sum+=t%10
    t//=10
  return sum