# -*- coding: utf-8 -*-
"""Copy of Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iMz0xpyxHdnaeT8ylgjjdPRFuzhw5duH
"""

class person:
  def __init__ (self,s,n):
    self.score=s
    self.name=n
    print('hello')