# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13YhMGIctBrevcFUdEOEtS_J3lTgZ_EPl
"""

class student:
  def __init__(self,id,name):
    self.id=id
    self.name=name