# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176Zs19mpyouezAB21yn62kMkgkVdJvNk
"""

def max_min_count(L):
  L.sort()
  count_min=L.count(L[0])
  count_max=L.count(L[-1])
  return L[-1],count_max,L[0],count_min