# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

class student:
  def __init__(self,id,name):
    self.id=id
    self.name=name