# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162i6dKr-Q9MrOlp_XLNmdoCsZUIBJyC3
"""

from os import name
class A:
  def __init__ (self,name):
    self.name=name
  def print(self):
     print(self.name)