# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

def mean():
  s=0
  for i in range(100):
      s+=int(input())
  return s/100