# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162i6dKr-Q9MrOlp_XLNmdoCsZUIBJyC3
"""

class car:
  def __init__ (self,name,w):
    self.name=name
    self.w=w
  def __it__ (self,other):
    return(self.w<other.w)