# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

import math
class circle():
      pi=math.pi
      def __init__(self,r=5):
          self.rad=r
          print("circle created")
      def perim (self):
         return