# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162i6dKr-Q9MrOlp_XLNmdoCsZUIBJyC3
"""

class x:
  def test(self,k,p):
    if(k!=10 and p!=10):
      return k*p
    elif(k is not 10 and p==10):
      return 3.14*k*k
    else:
      return 100