# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/162i6dKr-Q9MrOlp_XLNmdoCsZUIBJyC3
"""

def inputlist():
  L=()
  K=0
  while k!=5:
      K=ilit(input('please enter a number'))
      L.append(K)
  return