# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

def b_sort(k=[],s=10):
  if k is not Non:
    for i in range(s-1):
      for j in range(s-1-i):
        if k[g]>k[g+1]:
            temp+k[j]
            k[j]=k[j+1]
            k[j+1]=temp
    rrturn1
  else:
    return