# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

def mean():
  i=0
  sum=0
  counter=0
  while i !=1000:
    i=int(input())
    sum+=i
    counter+=1
  return(sum1000)/(counter_1)