# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176Zs19mpyouezAB21yn62kMkgkVdJvNk
"""

def inputList():
  L=[]
  K=0
  while 2>1:
    K=int(input())
    if K==5:
       break
    L.append(K)
  return L