# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/176Zs19mpyouezAB21yn62kMkgkVdJvNk
"""

def function1(n):
 for i in range (10*n):
  k=majmoe(i)
  if k==n:
    return k
 return print('not found')