# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wSjeBQSe1uhtG-h6U2eZ82nYBsGBLW-6
"""

def maximum100():
  a=input()
  a=inp(a)
  max=a
  for i in range(99):
      a=int(input())
      if a>max:
        max=c
  return max